use VETERINARIO;

-- A) QUAL A QUANTIDADE DE ANIMAIS REGISTRADAS NO SISTEMA?
select COUNT(*) QUANTIDADE_ANIMAL from ANIMAIS;

-- B) QUAL O TOTAL DE VACINAS APLICADAS REGISTRADAS NO SISTEMA?
select COUNT(*) QUANTIDADE_VACINA from VACINAS;

-- C) QUANTOS ANIMAIS TEMOS REGISTRADOS PARA CADA CATEGORIA?
select
	T.NOME as Categoria, 
    COUNT(A.ID) as Quantidade_Animais
from ANIMAIS A
join TIPO_ANIMAL T on A.ID_TIPO_ANIMAL = T.ID
group by T.NOME;

-- D) QUAL A CATEGORIA DE ANIMAIS QUE MAIS VACINAS RECEBEU?
select 
    T.NOME as Categoria,
    COUNT(V.ID) as Total_Vacinas
from VACINAS V
join ANIMAIS A on V.ID_ANIMAL = A.ID
join TIPO_ANIMAL T on A.ID_TIPO_ANIMAL = T.ID
group by T.NOME
order by Total_Vacinas desc
limit 1;
