create database UNIVERSIDADE;

use UNIVERSIDADE;

-- Criando as tabelas
CREATE TABLE PESSOA (
    ID_PESSOA INT PRIMARY KEY,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    TIPO_PESSOA VARCHAR(50) -- (organizador, ministrante, autor, membro comissão, participante)
);

CREATE TABLE SIMPOSIO (
    ID_SIMPÓSIO INT PRIMARY KEY,
    NOME VARCHAR(100),
    DATA DATE,
    LOCAL VARCHAR(100)
);

CREATE TABLE MINI_CURSO (
    ID_MINI_CURSO INT PRIMARY KEY,
    NOME VARCHAR(100),
    ID_PESSOA INT,
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
);

CREATE TABLE TEMA (
    ID_TEMA INT PRIMARY KEY,
    NOME VARCHAR(50)
);

CREATE TABLE ARTIGO (
    ID_ARTIGO INT PRIMARY KEY,
    TITULO VARCHAR(200),
    ID_TEMA INT,
    FOREIGN KEY (ID_TEMA) REFERENCES TEMA(ID_TEMA)
);

CREATE TABLE COMISSAO_CIENTIFICA (
    ID_COMISSAO INT PRIMARY KEY,
    ID_TEMA INT,
    FOREIGN KEY (ID_TEMA) REFERENCES TEMA(ID_TEMA)
);

CREATE TABLE INSCRICAO (
    ID_INSCRICAO INT PRIMARY KEY,
    ID_PESSOA INT,
    ID_SIMPÓSIO INT,
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA),
    FOREIGN KEY (ID_SIMPÓSIO) REFERENCES SIMPOSIO(ID_SIMPÓSIO)
);

CREATE TABLE AUTOR (
    ID_PESSOA INT,
    ID_ARTIGO INT,
    PRIMARY KEY (ID_PESSOA, ID_ARTIGO),
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA),
    FOREIGN KEY (ID_ARTIGO) REFERENCES ARTIGO(ID_ARTIGO)
);

CREATE TABLE COMPOSICAO_COMISSAO (
    ID_PESSOA INT,
    ID_COMISSAO INT,
    PRIMARY KEY (ID_PESSOA, ID_COMISSAO),
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA),
    FOREIGN KEY (ID_COMISSAO) REFERENCES COMISSAO_CIENTIFICA(ID_COMISSAO)
);

CREATE TABLE INSCRICAO_MINI_CURSO (
    ID_PESSOA INT,
    ID_MINI_CURSO INT,
    PRIMARY KEY (ID_PESSOA, ID_MINI_CURSO),
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA),
    FOREIGN KEY (ID_MINI_CURSO) REFERENCES MINI_CURSO(ID_MINI_CURSO)
);

-- Inserindo dados nas tabelas

-- Inserir pessoas
INSERT INTO PESSOA (ID_PESSOA, NOME, EMAIL, TIPO_PESSOA) VALUES (1, 'Maria Silva', 'maria@exemplo.com', 'organizador');
INSERT INTO PESSOA (ID_PESSOA, NOME, EMAIL, TIPO_PESSOA) VALUES (2, 'João Pereira', 'joao@exemplo.com', 'minstrante');
INSERT INTO PESSOA (ID_PESSOA, NOME, EMAIL, TIPO_PESSOA) VALUES (3, 'Carlos Souza', 'carlos@exemplo.com', 'autor');

-- Inserir temas
INSERT INTO TEMA (ID_TEMA, NOME) VALUES (1, 'Banco de Dados');
INSERT INTO TEMA (ID_TEMA, NOME) VALUES (2, 'Redes');
INSERT INTO TEMA (ID_TEMA, NOME) VALUES (3, 'Compiladores');

-- Inserir simpósio
INSERT INTO SIMPOSIO (ID_SIMPÓSIO, NOME, DATA, LOCAL) VALUES (1, 'Simpósio de Tecnologia', '2025-05-01', 'Auditório A');

-- Inserir mini cursos
INSERT INTO MINI_CURSO (ID_MINI_CURSO, NOME, ID_PESSOA) VALUES (1, 'Curso de Banco de Dados', 2);

-- Inserir artigos
INSERT INTO ARTIGO (ID_ARTIGO, TITULO, ID_TEMA) VALUES (1, 'Avanços em Banco de Dados', 1);

-- Inserir comissão científica
INSERT INTO COMISSAO_CIENTIFICA (ID_COMISSAO, ID_TEMA) VALUES (1, 1);

-- Inserir inscrição
INSERT INTO INSCRICAO (ID_INSCRICAO, ID_PESSOA, ID_SIMPÓSIO) VALUES (1, 3, 1);

-- Inserir autores
INSERT INTO AUTOR (ID_PESSOA, ID_ARTIGO) VALUES (3, 1);

-- Inserir membros da comissão
INSERT INTO COMPOSICAO_COMISSAO (ID_PESSOA, ID_COMISSAO) VALUES (1, 1);

-- Inserir inscrição no mini curso
INSERT INTO INSCRICAO_MINI_CURSO (ID_PESSOA, ID_MINI_CURSO) VALUES (3, 1);

